name: "Make bash script executable"

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout code
      uses: actions/checkout@v4

    - name: Step 2 - Run pipeline.sh
      run: ./pipeline.sh
